In [13]:
import numpy as np
Day_number=np.arange(1,11)
steps_walked=[4335,9552,7332,4504,5332,7552,8332,8504,8965,7689]
arr=np.array([Day_number,steps_walked])
arr=arr.T
arr

array([[   1, 4335],
       [   2, 9552],
       [   3, 7332],
       [   4, 4504],
       [   5, 5332],
       [   6, 7552],
       [   7, 8332],
       [   8, 8504],
       [   9, 8965],
       [  10, 7689]])

In [15]:
new_arr=arr[:,1]+2000

In [17]:
arr[:,1]=new_arr

In [18]:
arr

array([[    1,  6335],
       [    2, 11552],
       [    3,  9332],
       [    4,  6504],
       [    5,  7332],
       [    6,  9552],
       [    7, 10332],
       [    8, 10504],
       [    9, 10965],
       [   10,  9689]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [19]:
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[    2, 11552],
       [    3,  9332],
       [    6,  9552],
       [    7, 10332],
       [    8, 10504],
       [    9, 10965],
       [   10,  9689]])

In [ ]:
sortedArr=arr[arr[:]]